#!/bin/bash

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# md files: Compiles to pdf via pandoc
# rmd files: Compiles via R Markdown
# all others: run `sent` to show a presentation

oridir=$(pwd)

file=$(readlink -f "$1")
dir=$(dirname "$file")
ext="${file##*.}"
base="${file%.*}"
cd $dir

echo "Running compiler on $file"

# textype() { \
# 	command="pdflatex"
# 	( sed 5q "$file" | grep -i -q 'xelatex' ) && command="xelatex"
# 	$command --output-directory="$dir" "$base" &&
# 	grep -i addbibresource "$file" &&
# 	biber --input-directory "$dir" "$base" &&
# 	$command --output-directory="$dir" "$base" &&
# 	$command --output-directory="$dir" "$base"
# 	}

case "$ext" in
	# *\.rmd) echo "require(rmarkdown); render('$file')" | R --vanilla ;;
	# *\.tex) textype "$file" ;;
	tex|md) pandoc "$file" --pdf-engine=xelatex -o "$base".pdf ;;
	cpp|cc) g++ "$file" -o "$base".o ;;
    scss) sassc "$file" "$base".css ;;
esac
cd $oridir
