#!/bin/bash
# opout: "open output": A general handler for opening a file's intended output.
# I find this useful especially running from vim.

file=$(readlink -f "$1")
ext="${file##*.}"
filename="${file%.*}"

case "$ext" in
	tex|md|rmd) llpp $filename.pdf & ;;
    cpp|cc|h) $filename.o ;;
    py) python $file ;;
	html) $BROWSER $filename.html & ;;
    svg) feh --magick-timeout 1 $file ;;
    *) xdg-open $file
esac

